FORMAT: 1A
HOST: http://api.spiderlog.net

# Spider Log API
Provides services for the Spider Log app family, recording the world's spider sightings

# Group Spiders
Access to Spider resources

## My Spiders [/spiders{?page,size}]
### Get all my spider sightings [GET]

+ Parameters
    + page (required, number, `1`)... `page` number
    + size (required, number, `10`)... page `size`
    
+ Request

    + Header
    
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
        
+ Response 200 (application/json)

    + Header
    
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
            
    + Body

            {
                "page" :
                {
                    "number" : 1,
                    "size": 10,
                    "totalPages": 20
                },
                "spiders" :
                [
                    {
                        "sightedAt" : "2014-08-29T07:00",
                        "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-19247681/201408/14562881209_046a7f4d3d_z.jpg",
                        "description" : "Spider I saw on the train",
                        "tags": [
                            "stripy"
                        ]
                    }, 
                    {
                        "sightedAt" : "2014-08-29T13:00",
                        "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-19247681/201408/14587204878_91405ee2e1_z.jpg",
                        "description" : "Spider I saw at the office",
                        "tags": [
                            "big"
                        ]
                    },
                    {
                        "sightedAt" : "2014-08-29T19:00",
                        "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-19247681/201408/14776091214_4699046e5d_z.jpg",
                        "description" : "Spider I saw at home",
                        "tags": [
                            "big",
                            "stripy"
                        ]
                    }
                ]
            }

## Get my Spider [/spiders/{id}]
### Get one of my spider sightings [GET]

+ Parameters
    + id (required, string, `aba443c`)... `id` of the spider sighting
    
+ Request

    + Header
    
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
        
+ Response 200 (application/json)

    + Header
    
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
            
    + Body


            {
                "sightedAt" : "2014-08-29T07:00",
                "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-19247681/201408/14562881209_046a7f4d3d_z.jpg",
                "description" : "Spider I saw on the train",
                "tags": [
                    "stripy"
                ]
            }
    
## Create a new Spider [/spiders]
### Get one of my spider sightings [POST]

+ Request

    + Header
    
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            Content-type: application/json
            x-api-version: 1.0
    
    + Body

            {
                "sightedAt" : "2014-08-29T07:10",
                "imageUrl" : "https://s3-eu-west-1.amazonaws.com/uid-19247681/201408/14562881209_046a7f4d3d_z.jpg",
                "description" : "Another spider I saw on the train (or was it the same one?)",
                "tags": [
                    "stripy"
                ]
            }
        
+ Response 201 

    + Header
    
            Location : spiders/abbd4122

    